import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
      <Script src="https://unpkg.com/react@18/umd/react.production.min.js"></Script>
      <Script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></Script>
    </html>
  )
}
